<?php

add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );
function my_theme_enqueue_styles() {
    wp_enqueue_style( 'child-style', get_stylesheet_uri(),
        array( 'wyeth-style' ), 
        wp_get_theme()->get('Version') // this only works if you have Version in the style header
    );
}

/**
 * Register Custom Post Type for Tax People
 */
function brandywine_oak_create_post_types() {
  register_post_type( 'taxperson',
    array(
      'labels' => array(
        'name' => __( 'Tax Advisory People' ),
        'singular_name' => __( 'Tax Advisory Person' )
      ),
      'menu_icon'=>'dashicons-groups',
      'public' => true,
      'publicly_queryable' => true,
      'hierarchical' => false,
      'has_archive' => false,
      'query_var' => true,
      'rewrite' => array(
         'slug' => 'about-our-firm/our-tax-advisory-team',
         'with_front' => false
      ),
      'supports' => array( 'title', 'editor' ),
    )
  );
}
add_action( 'init', 'brandywine_oak_create_post_types' );

  // Add Tax Person Fields 
  acf_add_local_field_group(array(
    'key' => 'group_5b4eb64d08623',
    'title' => 'Person Content',
    'fields' => array(
      array(
        'key' => 'field_5b4eb6b18fa07',
        'label' => 'Person Name',
        'name' => 'person_name',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b4eb70c8fa09',
        'label' => 'Job Titles',
        'name' => 'job_titles',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => '',
        'sub_fields' => array(
          array(
            'key' => 'field_5b4eb7228fa0a',
            'label' => 'Text',
            'name' => 'text',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_5b4eb6e98fa08',
        'label' => 'Person Credentials',
        'name' => 'person_credentials',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b4eb825ebfe0',
        'label' => 'Person Email',
        'name' => 'person_email',
        'type' => 'email',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_5b4eb832ebfe1',
        'label' => 'Person LinkedIn',
        'name' => 'person_linkedin',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5b4eb801ebfdf',
        'label' => 'Person Image',
        'name' => 'person_image',
        'type' => 'image',
        'instructions' => 'Grid Image - 800px x 570px @72dpi',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_5b4eb801ebfdfport',
        'label' => 'Person Portrait Image',
        'name' => 'person_portrait_image',
        'type' => 'image',
        'instructions' => 'Bio Image - 700px x 1000px @72dpi',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_5b569fc5a82ecpers',
        'label' => 'Watermark',
        'name' => 'watermark',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 1,
        'layout' => 'table',
        'button_label' => '',
        'sub_fields' => array(
          array(
            'key' => 'field_5b569ffca82edpers',
            'label' => 'Watermark',
            'name' => 'watermark',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'th' => 'th',
              'w' => 'w',
              'wyeth' => 'wyeth',
              'y' => 'y',
              'bo' => 'bo',
              'ico' => 'ico'
            ),
            'default_value' => array(
              0 => 'th',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5b56a032a82eepers',
            'label' => 'Size',
            'name' => 'size',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'full' => 'full',
              'half' => 'half',
            ),
            'default_value' => array(
              0 => 'full',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5b56a05ea82efpers',
            'label' => 'X Position (Percent)',
            'name' => 'watermark_x',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
          array(
            'key' => 'field_5b56a07ea82f0pers',
            'label' => 'Y Position (Percent)',
            'name' => 'watermark_y',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'taxperson',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'discussion',
      1 => 'comments',
      2 => 'format',
      3 => 'categories',
      4 => 'tags',
    ),
    'active' => 1,
    'description' => '',
  ));

    // Page Content
    acf_add_local_field_group(array(
      'key' => 'group_5b4ea41e20ed4',
      'title' => 'Page Content',
      'fields' => array(
        array(
          'key' => 'field_5b4ea455758ef',
          'label' => 'Page Introduction',
          'name' => 'page_introduction',
          'type' => 'textarea',
          'instructions' => 'Header introductory text.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'maxlength' => '',
          'rows' => 4,
          'new_lines' => '',
        ),
        array(
          'key' => 'field_5b569fc5a82ecfoo',
          'label' => 'Footer Watermark',
          'name' => 'footer_watermark',
          'type' => 'repeater',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'collapsed' => '',
          'min' => 0,
          'max' => 1,
          'layout' => 'table',
          'button_label' => '',
          'sub_fields' => array(
            array(
              'key' => 'field_5b569ffca82edfoo',
              'label' => 'Watermark',
              'name' => 'watermark',
              'type' => 'select',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'th' => 'th',
                'w' => 'w',
                'wyeth' => 'wyeth',
                'y' => 'y',
                'bo' => 'bo',
                'ico' => 'ico'
              ),
              'default_value' => array(
                0 => 'th',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
            array(
              'key' => 'field_5b56a032a82eefoo',
              'label' => 'Size',
              'name' => 'size',
              'type' => 'select',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'full' => 'full',
                'half' => 'half',
              ),
              'default_value' => array(
                0 => 'full',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
            array(
              'key' => 'field_5b56a05ea82effoo',
              'label' => 'X Position (Percent)',
              'name' => 'watermark_x',
              'type' => 'number',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'min' => '',
              'max' => '',
              'step' => '',
            ),
            array(
              'key' => 'field_5b56a07ea82f0foo',
              'label' => 'Y Position (Percent)',
              'name' => 'watermark_y',
              'type' => 'number',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'min' => '',
              'max' => '',
              'step' => '',
            ),
          ),
        ),
        array(
          'key' => 'field_5b4ea5cf758f0',
          'label' => 'Page Content',
          'name' => 'page_content',
          'type' => 'flexible_content',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'layouts' => array(
            '5b4ea5db9b1b7' => array(
              'key' => '5b4ea5db9b1b7',
              'name' => 'content_block',
              'label' => 'Content Block',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5b4ea668758f3',
                  'label' => 'Style',
                  'name' => 'style',
                  'type' => 'select',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'navy' => 'Navy',
                    'white' => 'White',
                  ),
                  'default_value' => array(
                    0 => 'Navy',
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'ui' => 0,
                  'ajax' => 0,
                  'return_format' => 'value',
                  'placeholder' => '',
                ),
                array(
                  'key' => 'field_5b4ea60f758f1',
                  'label' => 'Title',
                  'name' => 'title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5b4ea61f758f2',
                  'label' => 'Introduction',
                  'name' => 'introduction',
                  'type' => 'wysiwyg',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'all',
                  'toolbar' => 'full',
                  'media_upload' => 0,
                  'delay' => 0,
                ),
                array(
                  'key' => 'field_5b4ea6a7758f4',
                  'label' => 'Main Content',
                  'name' => 'main_content',
                  'type' => 'wysiwyg',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'all',
                  'toolbar' => 'full',
                  'media_upload' => 1,
                  'delay' => 0,
                ),
                array(
                  'key' => 'field_5b4ea6cb758f5',
                  'label' => 'Sidebar Content',
                  'name' => 'sidebar_content',
                  'type' => 'wysiwyg',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'all',
                  'toolbar' => 'full',
                  'media_upload' => 1,
                  'delay' => 0,
                ),
                array(
                  'key' => 'field_5b569fc5a82ec',
                  'label' => 'Watermark',
                  'name' => 'watermark',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 0,
                  'max' => 1,
                  'layout' => 'table',
                  'button_label' => '',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5b569ffca82ed',
                      'label' => 'Watermark',
                      'name' => 'watermark',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'th' => 'th',
                        'w' => 'w',
                        'wyeth' => 'wyeth',
                        'y' => 'y',
                        'bo' => 'bo',
                        'ico' => 'ico'
                      ),
                      'default_value' => array(
                        0 => 'th',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a032a82ee',
                      'label' => 'Size',
                      'name' => 'size',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'full' => 'full',
                        'half' => 'half',
                      ),
                      'default_value' => array(
                        0 => 'full',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a05ea82ef',
                      'label' => 'X Position (Percent)',
                      'name' => 'watermark_x',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                    array(
                      'key' => 'field_5b56a07ea82f0',
                      'label' => 'Y Position (Percent)',
                      'name' => 'watermark_y',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                  ),
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'yX10tYWupBXj' => array(
              'key' => 'yX10tYWupBXj',
              'name' => 'contact_block',
              'label' => 'Contact Block',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5b4ea60f758f1',
                  'label' => 'Title',
                  'name' => 'title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_Mf306gJVRlh0',
                  'label' => 'Main Contact',
                  'name' => 'main_contact',
                  'type' => 'wysiwyg',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'all',
                  'toolbar' => 'full',
                  'media_upload' => 1,
                  'delay' => 0,
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            '5b4ea9142ba2c' => array(
              'key' => '5b4ea9142ba2c',
              'name' => 'image_block',
              'label' => 'Image Block',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5b4ea91d2ba2d',
                  'label' => 'Large Image',
                  'name' => 'large_image',
                  'type' => 'image',
                  'instructions' => 'Hidden on Mobile Screens 1000px x 650px @ 72dpi',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
                array(
                  'key' => 'field_5b4ea9632ba2e',
                  'label' => 'Small Image',
                  'name' => 'small_image',
                  'type' => 'image',
                  'instructions' => '640px x 410px @ 72dpi',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            '5b4eaa7fab350' => array(
              'key' => '5b4eaa7fab350',
              'name' => 'form_block',
              'label' => 'Form Block',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5b4eaa86ab351',
                  'label' => 'Form Shortcode',
                  'name' => 'form_shortcode',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5b569fc5a82ecform',
                  'label' => 'Watermark',
                  'name' => 'watermark',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 0,
                  'max' => 1,
                  'layout' => 'table',
                  'button_label' => '',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5b569ffca82edform',
                      'label' => 'Watermark',
                      'name' => 'watermark',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'th' => 'th',
                        'w' => 'w',
                        'wyeth' => 'wyeth',
                        'y' => 'y',
                        'bo' => 'bo',
                        'ico' => 'ico'
                      ),
                      'default_value' => array(
                        0 => 'th',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a032a82eeform',
                      'label' => 'Size',
                      'name' => 'size',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'full' => 'full',
                        'half' => 'half',
                      ),
                      'default_value' => array(
                        0 => 'full',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a05ea82efform',
                      'label' => 'X Position (Percent)',
                      'name' => 'watermark_x',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                    array(
                      'key' => 'field_5b56a07ea82f0form',
                      'label' => 'Y Position (Percent)',
                      'name' => 'watermark_y',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                  ),
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            '5b4ea75f25fa8' => array(
              'key' => '5b4ea75f25fa8',
              'name' => 'logo_grid',
              'label' => 'Logo Grid',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5b4ea77825fa9',
                  'label' => 'Title',
                  'name' => 'title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5b4ea79a25faa',
                  'label' => 'Grid Items',
                  'name' => 'grid_items',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 0,
                  'max' => 0,
                  'layout' => 'block',
                  'button_label' => '',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5b4ea7ca25fab',
                      'label' => 'Title',
                      'name' => 'title',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                    array(
                      'key' => 'field_5b4ea7db25fac',
                      'label' => 'Logo',
                      'name' => 'logo',
                      'type' => 'image',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                      ),
                      'return_format' => 'url',
                      'preview_size' => 'thumbnail',
                      'library' => 'all',
                      'min_width' => '',
                      'min_height' => '',
                      'min_size' => '',
                      'max_width' => '',
                      'max_height' => '',
                      'max_size' => '',
                      'mime_types' => '',
                    ),
                    array(
                      'key' => 'field_5b4ec88f8e3f5',
                      'label' => 'Logo Width',
                      'name' => 'logo_width',
                      'type' => 'number',
                      'instructions' => 'As percent of container.',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                    array(
                      'key' => 'field_5b4ea80d25fad',
                      'label' => 'Link',
                      'name' => 'link',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                    array(
                      'key' => 'field_5b4ea82725fae',
                      'label' => 'Content',
                      'name' => 'content',
                      'type' => 'wysiwyg',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '66',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'tabs' => 'all',
                      'toolbar' => 'full',
                      'media_upload' => 0,
                      'delay' => 0,
                    ),
                  ),
                ),
                array(
                  'key' => 'field_5b569fc5a82eclogo',
                  'label' => 'Watermark',
                  'name' => 'watermark',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 0,
                  'max' => 1,
                  'layout' => 'table',
                  'button_label' => '',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5b569ffca82edlogo',
                      'label' => 'Watermark',
                      'name' => 'watermark',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'th' => 'th',
                        'w' => 'w',
                        'wyeth' => 'wyeth',
                        'y' => 'y',
                        'bo' => 'bo',
                        'ico' => 'ico'
                      ),
                      'default_value' => array(
                        0 => 'th',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a032a82eelogo',
                      'label' => 'Size',
                      'name' => 'size',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'full' => 'full',
                        'half' => 'half',
                      ),
                      'default_value' => array(
                        0 => 'full',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a05ea82eflogo',
                      'label' => 'X Position (Percent)',
                      'name' => 'watermark_x',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                    array(
                      'key' => 'field_5b56a07ea82f0logo',
                      'label' => 'Y Position (Percent)',
                      'name' => 'watermark_y',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                  ),
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            '5b4eaa1fbbc7e' => array(
              'key' => '5b4eaa1fbbc7e',
              'name' => 'map_block',
              'label' => 'Map Block',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5b4eaa24bbc7f',
                  'label' => 'Map Embed Code',
                  'name' => 'map_embed_code',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 3,
                  'new_lines' => '',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            '5b4ea85970e42' => array(
              'key' => '5b4ea85970e42',
              'name' => 'process_block',
              'label' => 'Process Block',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5b4ea86e70e43',
                  'label' => 'Title',
                  'name' => 'title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5b4ea87770e44',
                  'label' => 'Process Steps',
                  'name' => 'process_steps',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 0,
                  'max' => 0,
                  'layout' => 'table',
                  'button_label' => '',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5b4ea89470e45',
                      'label' => 'Step Content',
                      'name' => 'step_content',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                  ),
                ),
                array(
                  'key' => 'field_5b569fc5a82ecpro',
                  'label' => 'Watermark',
                  'name' => 'watermark',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 0,
                  'max' => 1,
                  'layout' => 'table',
                  'button_label' => '',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5b569ffca82edpro',
                      'label' => 'Watermark',
                      'name' => 'watermark',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'th' => 'th',
                        'w' => 'w',
                        'wyeth' => 'wyeth',
                        'y' => 'y',
                        'bo' => 'bo',
                        'ico' => 'ico'
                      ),
                      'default_value' => array(
                        0 => 'th',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a032a82eepro',
                      'label' => 'Size',
                      'name' => 'size',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'full' => 'full',
                        'half' => 'half',
                      ),
                      'default_value' => array(
                        0 => 'full',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a05ea82efpro',
                      'label' => 'X Position (Percent)',
                      'name' => 'watermark_x',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                    array(
                      'key' => 'field_5b56a07ea82f0pro',
                      'label' => 'Y Position (Percent)',
                      'name' => 'watermark_y',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                  ),
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            '5b4ea8ca0ea1c' => array(
              'key' => '5b4ea8ca0ea1c',
              'name' => 'team_grid',
              'label' => 'Team Grid',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5b569fc5a82ecteam',
                  'label' => 'Watermark',
                  'name' => 'watermark',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 0,
                  'max' => 1,
                  'layout' => 'table',
                  'button_label' => '',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5b569ffca82edteam',
                      'label' => 'Watermark',
                      'name' => 'watermark',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'th' => 'th',
                        'w' => 'w',
                        'wyeth' => 'wyeth',
                        'y' => 'y',
                        'bo' => 'bo',
                        'ico' => 'ico'
                      ),
                      'default_value' => array(
                        0 => 'th',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a032a82eeteam',
                      'label' => 'Size',
                      'name' => 'size',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'full' => 'full',
                        'half' => 'half',
                      ),
                      'default_value' => array(
                        0 => 'full',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a05ea82efteam',
                      'label' => 'X Position (Percent)',
                      'name' => 'watermark_x',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                    array(
                      'key' => 'field_5b56a07ea82f0team',
                      'label' => 'Y Position (Percent)',
                      'name' => 'watermark_y',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                  ),
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            '5b4eaaba20f4a' => array(
              'key' => '5b4eaaba20f4a',
              'name' => 'text_grid',
              'label' => 'Text Grid',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5b4eaac520f4b',
                  'label' => 'Grid Items',
                  'name' => 'grid_items',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 0,
                  'max' => 0,
                  'layout' => 'table',
                  'button_label' => '',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5b4eaad620f4c',
                      'label' => 'Title',
                      'name' => 'title',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                    array(
                      'key' => 'field_5b4eaaeb20f4d',
                      'label' => 'Content',
                      'name' => 'content',
                      'type' => 'wysiwyg',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'tabs' => 'all',
                      'toolbar' => 'full',
                      'media_upload' => 0,
                      'delay' => 0,
                    ),
                    array(
                      'key' => 'field_5b4ea91d2ba2dasdf',
                      'label' => 'Image',
                      'name' => 'image',
                      'type' => 'image',
                      'instructions' => 'Displays instead of content.',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'return_format' => 'url',
                      'preview_size' => 'thumbnail',
                      'library' => 'all',
                      'min_width' => '',
                      'min_height' => '',
                      'min_size' => '',
                      'max_width' => '',
                      'max_height' => '',
                      'max_size' => '',
                      'mime_types' => '',
                    ),
                  ),
                ),
                array(
                  'key' => 'field_5b569fc5a82ectext',
                  'label' => 'Watermark',
                  'name' => 'watermark',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 0,
                  'max' => 1,
                  'layout' => 'table',
                  'button_label' => '',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5b569ffca82edtext',
                      'label' => 'Watermark',
                      'name' => 'watermark',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'th' => 'th',
                        'w' => 'w',
                        'wyeth' => 'wyeth',
                        'y' => 'y',
                        'bo' => 'bo',
                        'ico' => 'ico'
                      ),
                      'default_value' => array(
                        0 => 'th',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a032a82eetext',
                      'label' => 'Size',
                      'name' => 'size',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'full' => 'full',
                        'half' => 'half',
                      ),
                      'default_value' => array(
                        0 => 'full',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a05ea82eftext',
                      'label' => 'X Position (Percent)',
                      'name' => 'watermark_x',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                    array(
                      'key' => 'field_5b56a07ea82f0text',
                      'label' => 'Y Position (Percent)',
                      'name' => 'watermark_y',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                  ),
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            '5b4ea9cdfe833' => array(
              'key' => '5b4ea9cdfe833',
              'name' => 'text_slideshow',
              'label' => 'Text Slideshow',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5b4ea9effe834',
                  'label' => 'Slides',
                  'name' => 'slides',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 0,
                  'max' => 0,
                  'layout' => 'table',
                  'button_label' => '',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5b4ea9fbfe835',
                      'label' => 'Slide Text',
                      'name' => 'slide_text',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                  ),
                ),
                array(
                  'key' => 'field_5b569fc5a82ecsli',
                  'label' => 'Watermark',
                  'name' => 'watermark',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 0,
                  'max' => 1,
                  'layout' => 'table',
                  'button_label' => '',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5b569ffca82edsli',
                      'label' => 'Watermark',
                      'name' => 'watermark',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'th' => 'th',
                        'w' => 'w',
                        'wyeth' => 'wyeth',
                        'y' => 'y',
                        'bo' => 'bo',
                        'ico' => 'ico'
                      ),
                      'default_value' => array(
                        0 => 'th',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a032a82eesli',
                      'label' => 'Size',
                      'name' => 'size',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'full' => 'full',
                        'half' => 'half',
                      ),
                      'default_value' => array(
                        0 => 'full',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'return_format' => 'value',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5b56a05ea82efsli',
                      'label' => 'X Position (Percent)',
                      'name' => 'watermark_x',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                    array(
                      'key' => 'field_5b56a07ea82f0sli',
                      'label' => 'Y Position (Percent)',
                      'name' => 'watermark_y',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                    ),
                  ),
                ),
              ),
              'min' => '',
              'max' => '',
            ),
          ),
          'button_label' => 'Add Row',
          'min' => '',
          'max' => '',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'page_template',
            'operator' => '==',
            'value' => 'default',
          ),
        ),
        array(
          array(
            'param' => 'page_template',
            'operator' => '==',
            'value' => 'page-contact.php',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => array(
        0 => 'the_content',
        1 => 'discussion',
        2 => 'comments',
        3 => 'categories',
        4 => 'tags',
      ),
      'active' => 1,
      'description' => '',
    ));
  